
build: off
stack: node 8, python 3.8.2
skip_tags: true
environment:
  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        ADO_ARTIFACTORY_SKIP_TESTS:  maven,npm,go,gradle,conan,docker

  nodejs_version: "8"
  ADO_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  ADO_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  ADO_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  ADO_ARTIFACTORY_DOCKER_DOMAIN:
    secure: ppjr6mrLIKXVptLX8WPOlffTwOLtRIoaIpsVEvmje/9mDtLojTqpwI9OIC5VZnx1
  ADO_ARTIFACTORY_DOCKER_REPO:
    secure: UjixvF6E1Bp1p8zgPRLCVA==

install:
- appveyor DownloadFile https://ecosysjfrog.jfrog.io/artifactory/liron-test/1.37.0/jfrog-cli-linux-amd64/jfrog -FileName jfrog
- sh: chmod 555 ./jfrog
- sh: sudo cp ./jfrog /usr/bin/
- sh: sudo pip install conan -q
- cmd: pip install conan -q
- cmd: nuget update -self

services:
- docker

test_script:
- which mono
- which nuget
- mono --version
- nuget ?
- jfrog --version
- node --version
- npm --version
- npm t
- npm run create # Make sure that that the extension can be created
